adult(72,private,5,exec_managerial,asian_pac_islander,female,48,united_states).
adult(39,private,14,exec_managerial,white,male,40,cuba).
adult(47,private,11,machine_op_inspct,white,male,40,united_states).
adult(32,private,12,exec_managerial,white,female,40,united_states).
adult(63,self_emp_not_inc,10,prof_specialty,white,female,10,united_states).
adult(36,private,10,exec_managerial,white,male,40,united_states).
adult(27,self_emp_not_inc,13,exec_managerial,white,male,60,united_states).
adult(28,private,9,craft_repair,white,male,42,united_states).
adult(53,private,13,sales,white,male,50,united_states).
adult(37,state_gov,11,prof_specialty,white,male,40,united_states).
adult(42,local_gov,14,exec_managerial,white,male,40,united_states).
adult(46,private,9,exec_managerial,white,male,40,united_states).
adult(37,private,13,other_service,asian_pac_islander,female,30,united_states).
adult(51,local_gov,10,exec_managerial,black,male,40,united_states).
adult(36,local_gov,10,protective_serv,white,male,40,united_states).
adult(34,private,13,exec_managerial,white,male,40,united_states).
adult(37,private,14,exec_managerial,white,male,60,united_states).
adult(51,self_emp_inc,12,sales,white,male,38,united_states).
adult(31,federal_gov,9,adm_clerical,white,female,40,united_states).
adult(37,private,9,other_service,white,male,44,united_states).
adult(42,private,12,sales,white,male,45,united_states).
adult(51,private,13,sales,white,male,47,united_states).
adult(49,private,10,craft_repair,white,male,40,united_states).
adult(52,private,10,prof_specialty,white,male,45,united_states).
adult(47,state_gov,13,exec_managerial,white,female,40,united_states).
adult(43,self_emp_inc,10,sales,white,male,55,united_states).
adult(42,private,9,craft_repair,white,male,40,united_states).
adult(66,private,10,sales,white,male,40,united_states).
adult(30,private,9,protective_serv,white,male,60,united_states).
adult(45,private,10,adm_clerical,white,female,35,united_states).
adult(44,local_gov,9,other_service,black,female,38,jamaica).
adult(46,private,13,exec_managerial,white,male,50,united_states).
adult(44,private,14,prof_specialty,white,male,35,united_states).
adult(33,self_emp_inc,13,sales,white,male,50,united_states).
adult(57,self_emp_inc,14,sales,white,male,65,united_states).
adult(47,self_emp_not_inc,3,sales,white,male,55,italy).
adult(41,private,9,exec_managerial,white,male,40,united_states).
adult(45,private,13,exec_managerial,white,male,40,united_states).
adult(27,private,13,prof_specialty,white,female,40,united_states).
adult(37,private,12,machine_op_inspct,white,male,40,united_states).
adult(54,self_emp_not_inc,13,exec_managerial,white,male,45,united_states).
adult(36,private,12,exec_managerial,white,female,50,united_states).
adult(41,self_emp_not_inc,14,sales,white,male,5,united_states).
adult(63,self_emp_inc,14,sales,white,male,68,united_states).
adult(50,private,7,transport_moving,white,male,70,united_states).
adult(49,private,10,craft_repair,white,male,40,united_states).
adult(50,private,13,adm_clerical,white,female,40,united_states).
adult(47,private,9,machine_op_inspct,black,female,40,united_states).
adult(45,private,9,transport_moving,white,male,40,united_states).
adult(33,private,10,sales,white,male,48,united_states).
adult(45,private,14,exec_managerial,white,male,50,united_states).
adult(32,local_gov,13,prof_specialty,white,female,50,united_states).
adult(42,private,12,adm_clerical,black,female,40,united_states).
adult(59,self_emp_not_inc,13,sales,white,male,40,united_states).
adult(35,private,11,sales,white,male,50,germany).
adult(60,private,9,tech_support,white,female,40,united_states).
adult(37,state_gov,13,prof_specialty,white,male,55,united_states).
adult(38,federal_gov,15,prof_specialty,white,male,50,united_states).
adult(51,private,11,handlers_cleaners,white,male,40,united_states).
adult(45,private,12,craft_repair,white,male,45,united_states).
adult(51,private,10,craft_repair,white,male,40,united_states).
adult(44,federal_gov,13,adm_clerical,asian_pac_islander,male,40,philippines).
adult(44,private,16,adm_clerical,white,male,55,united_states).
adult(63,self_emp_inc,9,exec_managerial,white,male,40,united_states).
adult(29,private,14,sales,white,male,40,united_states).
adult(43,private,10,sales,white,male,50,united_states).
adult(31,private,9,other_service,white,male,40,mexico).
adult(41,private,14,prof_specialty,asian_pac_islander,male,55,taiwan).
adult(46,local_gov,13,prof_specialty,white,male,35,united_states).
adult(52,private,10,craft_repair,white,male,40,united_states).
adult(45,private,13,sales,white,male,40,united_states).
adult(30,private,13,other_service,white,female,40,united_states).
adult(53,private,13,prof_specialty,white,male,40,united_states).
adult(42,private,10,prof_specialty,white,male,40,united_states).
adult(26,private,13,sales,white,female,40,united_states).
adult(62,state_gov,14,prof_specialty,white,male,60,united_states).
adult(65,self_emp_inc,13,sales,white,male,60,united_states).
adult(45,local_gov,10,protective_serv,white,male,40,united_states).
adult(63,federal_gov,14,exec_managerial,white,male,50,united_states).
adult(39,private,13,exec_managerial,white,male,50,united_states).
adult(53,federal_gov,10,exec_managerial,asian_pac_islander,female,40,philippines).
adult(23,self_emp_not_inc,7,transport_moving,white,male,60,united_states).
adult(51,private,10,exec_managerial,white,male,65,united_states).
adult(36,private,14,exec_managerial,asian_pac_islander,male,40,taiwan).
adult(44,private,14,exec_managerial,white,male,40,united_states).
adult(29,private,13,sales,white,male,40,united_states).
adult(62,self_emp_not_inc,8,craft_repair,white,male,40,united_states).
adult(31,private,13,exec_managerial,white,female,50,united_states).
adult(37,private,13,exec_managerial,white,male,40,united_states).
adult(47,private,9,other_service,white,male,40,united_states).
adult(26,private,15,prof_specialty,white,male,60,united_states).
adult(36,private,10,craft_repair,white,male,44,united_states).
adult(34,self_emp_inc,14,prof_specialty,white,female,40,united_states).
adult(54,private,9,machine_op_inspct,white,male,40,england).
adult(56,self_emp_inc,13,sales,white,male,50,united_states).
adult(33,self_emp_not_inc,13,sales,white,male,45,united_states).
adult(30,self_emp_inc,9,exec_managerial,white,male,65,canada).
adult(53,private,14,prof_specialty,white,female,54,united_states).
adult(57,private,13,exec_managerial,white,male,40,united_states).
adult(48,private,10,exec_managerial,white,male,40,united_states).
adult(44,private,13,exec_managerial,white,male,50,united_states).
adult(39,local_gov,14,prof_specialty,white,male,40,united_states).
adult(34,private,9,machine_op_inspct,white,male,44,united_states).
adult(55,self_emp_inc,15,prof_specialty,white,male,35,greece).
adult(60,private,9,craft_repair,white,male,40,united_states).
adult(61,self_emp_not_inc,9,craft_repair,white,male,52,united_states).
adult(42,state_gov,13,exec_managerial,white,male,50,united_states).
adult(38,private,11,craft_repair,white,male,40,united_states).
adult(64,private,13,exec_managerial,white,male,40,united_states).
adult(39,private,9,sales,white,male,44,united_states).
adult(39,self_emp_not_inc,9,sales,black,female,54,dominican_republic).
adult(50,federal_gov,14,tech_support,white,male,40,united_states).
adult(30,private,11,tech_support,white,female,40,canada).
adult(39,self_emp_inc,13,sales,white,male,60,united_states).
adult(44,self_emp_inc,13,exec_managerial,white,male,52,united_states).
adult(40,private,16,prof_specialty,white,male,40,united_states).
adult(50,private,13,transport_moving,white,male,40,united_states).
adult(32,private,10,exec_managerial,white,male,60,united_states).
adult(57,private,13,sales,white,male,40,united_states).
adult(57,self_emp_not_inc,9,craft_repair,white,male,55,united_states).
adult(34,self_emp_not_inc,9,craft_repair,white,male,45,united_states).
adult(31,private,12,craft_repair,asian_pac_islander,male,50,united_states).
adult(29,private,10,transport_moving,white,male,45,united_states).
adult(51,private,13,exec_managerial,white,male,60,united_states).
adult(36,self_emp_not_inc,10,craft_repair,white,male,60,united_states).
adult(49,federal_gov,14,exec_managerial,white,male,56,united_states).
adult(47,private,9,machine_op_inspct,white,male,50,united_states).
adult(34,private,10,adm_clerical,black,male,40,united_states).
adult(24,private,10,transport_moving,white,male,70,united_states).
adult(55,private,13,sales,white,male,50,united_states).
adult(39,private,11,adm_clerical,white,female,20,united_states).
adult(56,self_emp_inc,10,exec_managerial,white,male,50,united_states).
adult(34,private,13,prof_specialty,white,male,50,united_states).
adult(32,self_emp_inc,9,sales,white,male,65,united_states).
adult(52,private,9,transport_moving,white,male,60,united_states).
adult(41,private,13,exec_managerial,white,male,50,united_states).
adult(33,private,10,exec_managerial,white,male,50,united_states).
adult(46,private,13,craft_repair,white,male,45,united_states).
adult(39,private,14,exec_managerial,black,male,52,united_states).
adult(37,private,11,prof_specialty,white,female,45,united_states).
adult(41,private,9,transport_moving,white,male,50,united_states).
adult(60,private,12,adm_clerical,white,male,35,united_states).
adult(24,private,9,exec_managerial,white,female,45,united_states).
adult(45,private,13,exec_managerial,white,male,55,united_states).
adult(41,private,13,exec_managerial,white,male,40,united_states).
adult(31,private,11,sales,white,male,40,united_states).
adult(41,federal_gov,9,transport_moving,white,male,40,united_states).
adult(42,private,12,craft_repair,white,male,50,united_states).
adult(52,federal_gov,9,exec_managerial,white,male,40,united_states).
adult(32,private,13,tech_support,white,male,40,united_states).
adult(55,self_emp_inc,13,sales,white,male,60,united_states).
adult(33,private,13,exec_managerial,white,female,40,united_states).
adult(47,private,11,craft_repair,white,male,40,united_states).
adult(34,private,13,prof_specialty,white,male,40,iran).
adult(48,private,9,craft_repair,white,male,45,united_states).
adult(48,state_gov,11,prof_specialty,white,female,56,united_states).
adult(40,private,13,exec_managerial,white,female,40,united_states).
adult(70,private,13,sales,white,male,70,united_states).
adult(49,private,10,exec_managerial,white,female,40,united_states).
adult(51,private,9,handlers_cleaners,white,male,40,united_states).
adult(37,private,9,tech_support,white,male,40,united_states).
adult(55,state_gov,14,prof_specialty,white,male,45,united_states).
adult(47,private,9,transport_moving,white,male,55,united_states).
adult(52,self_emp_not_inc,15,prof_specialty,white,male,45,united_states).
adult(50,private,10,tech_support,white,male,45,united_states).
adult(39,private,10,exec_managerial,white,female,40,united_states).
adult(42,state_gov,14,prof_specialty,white,female,20,united_states).
adult(39,private,9,sales,white,male,50,united_states).
adult(34,private,10,sales,white,male,55,united_states).
adult(45,local_gov,13,prof_specialty,white,female,50,united_states).
adult(28,private,14,prof_specialty,white,female,40,united_states).
adult(30,federal_gov,13,prof_specialty,white,male,40,united_states).
adult(62,private,15,prof_specialty,white,male,30,united_states).
adult(32,private,9,craft_repair,white,male,40,united_states).
adult(37,local_gov,9,protective_serv,white,male,40,united_states).
adult(37,private,10,adm_clerical,white,female,45,united_states).
adult(38,private,13,exec_managerial,white,male,40,united_states).
adult(43,private,10,sales,white,male,40,united_states).
adult(53,self_emp_not_inc,4,exec_managerial,white,male,50,greece).
adult(43,private,13,sales,white,male,65,united_states).
adult(43,local_gov,14,exec_managerial,white,male,60,united_states).
adult(48,private,9,exec_managerial,white,male,50,united_states).
adult(51,private,9,craft_repair,white,male,45,united_states).
adult(41,private,13,transport_moving,white,male,48,canada).
adult(55,private,13,tech_support,white,male,18,united_states).
adult(61,private,10,sales,white,male,45,united_states).
adult(43,federal_gov,14,protective_serv,white,male,60,united_states).
adult(47,self_emp_inc,15,prof_specialty,white,male,60,united_states).
adult(47,private,13,prof_specialty,white,male,40,united_states).
adult(41,private,2,machine_op_inspct,white,male,40,mexico).
adult(54,self_emp_not_inc,13,exec_managerial,white,male,40,united_states).
adult(36,private,14,prof_specialty,white,male,60,united_states).
adult(57,self_emp_not_inc,10,sales,white,male,60,united_states).
adult(58,self_emp_inc,15,prof_specialty,white,male,50,united_states).
adult(44,private,15,prof_specialty,white,male,40,united_states).
adult(41,local_gov,10,other_service,white,male,40,united_states).
adult(37,self_emp_inc,9,sales,white,male,60,united_states).
adult(50,private,10,sales,white,male,45,united_states).
adult(36,private,10,exec_managerial,white,male,60,united_states).
adult(40,self_emp_not_inc,15,prof_specialty,white,male,45,united_states).
adult(47,private,14,sales,white,male,40,united_states).
adult(47,local_gov,9,protective_serv,white,male,60,united_states).
adult(38,federal_gov,12,adm_clerical,white,female,33,united_states).
adult(45,private,14,exec_managerial,white,female,50,united_states).
adult(39,private,9,craft_repair,white,male,50,united_states).
adult(48,private,13,exec_managerial,white,male,45,united_states).
adult(46,private,9,machine_op_inspct,white,male,40,united_states).
adult(47,private,9,transport_moving,white,male,48,italy).
adult(67,self_emp_inc,13,exec_managerial,white,male,75,united_states).
adult(30,private,9,tech_support,white,male,40,united_states).
adult(40,private,9,sales,white,male,60,united_states).
adult(49,private,12,sales,white,female,40,united_states).
adult(29,self_emp_not_inc,15,prof_specialty,white,male,50,italy).
adult(75,private,10,exec_managerial,white,male,35,united_states).
adult(45,private,13,prof_specialty,white,male,55,united_states).
adult(27,private,13,prof_specialty,white,male,42,united_states).
adult(60,private,13,exec_managerial,white,male,35,united_states).
adult(42,private,11,prof_specialty,white,male,40,united_states).
adult(38,private,10,exec_managerial,white,male,44,united_states).
adult(49,self_emp_inc,13,sales,white,male,52,united_states).
adult(36,private,13,prof_specialty,white,male,45,united_states).
adult(36,private,9,sales,white,male,40,united_states).
adult(61,private,10,sales,white,male,44,united_states).
adult(37,private,14,exec_managerial,white,male,40,united_states).
adult(64,local_gov,7,craft_repair,black,male,40,united_states).
