adult(52,self_emp_not_inc,9,exec_managerial,white,male,45,united_states).
adult(31,private,14,prof_specialty,white,female,50,united_states).
adult(42,private,13,exec_managerial,white,male,40,united_states).
adult(37,private,10,exec_managerial,black,male,80,united_states).
adult(30,state_gov,13,prof_specialty,asian_pac_islander,male,40,india).
adult(43,self_emp_not_inc,14,exec_managerial,white,female,45,united_states).
adult(40,private,16,prof_specialty,white,male,60,united_states).
adult(56,local_gov,13,tech_support,white,male,40,united_states).
adult(57,federal_gov,13,prof_specialty,black,male,40,united_states).
adult(47,private,15,prof_specialty,white,female,60,honduras).
adult(50,federal_gov,13,exec_managerial,white,male,55,united_states).
adult(43,private,10,tech_support,white,male,40,united_states).
adult(42,private,16,prof_specialty,white,male,45,united_states).
adult(53,private,9,adm_clerical,white,female,40,united_states).
adult(49,self_emp_inc,10,exec_managerial,white,male,50,united_states).
adult(29,self_emp_not_inc,13,sales,white,male,70,united_states).
adult(44,private,9,craft_repair,white,female,40,united_states).
adult(49,local_gov,9,protective_serv,white,male,40,united_states).
adult(43,federal_gov,16,prof_specialty,white,female,50,united_states).
adult(34,local_gov,13,protective_serv,white,male,40,united_states).
adult(48,self_emp_not_inc,16,prof_specialty,white,male,60,united_states).
adult(37,private,10,sales,white,male,48,united_states).
adult(76,private,14,exec_managerial,white,male,40,united_states).
adult(44,private,13,exec_managerial,white,male,60,united_states).
adult(32,self_emp_inc,9,craft_repair,white,male,40,united_states).
adult(38,private,15,prof_specialty,white,male,40,united_states).
adult(56,self_emp_not_inc,9,other_service,white,male,50,canada).
adult(49,local_gov,11,craft_repair,black,male,40,united_states).
adult(29,state_gov,13,prof_specialty,white,male,50,united_states).
adult(47,private,13,exec_managerial,white,female,40,united_states).
adult(31,private,12,adm_clerical,white,male,40,united_states).
adult(38,federal_gov,14,prof_specialty,white,male,40,iran).
adult(49,private,10,craft_repair,asian_pac_islander,male,40,united_states).
adult(45,private,11,prof_specialty,white,female,40,united_states).
adult(45,self_emp_not_inc,14,sales,white,male,40,united_states).
adult(51,private,10,sales,white,male,40,united_states).
adult(28,state_gov,13,prof_specialty,white,male,40,united_states).
adult(44,local_gov,10,exec_managerial,black,male,38,united_states).
adult(40,private,4,machine_op_inspct,white,male,40,mexico).
adult(37,federal_gov,10,adm_clerical,white,male,42,united_states).
adult(58,state_gov,16,prof_specialty,white,male,1,united_states).
adult(40,federal_gov,14,exec_managerial,white,female,55,united_states).
adult(35,private,14,prof_specialty,white,male,40,united_states).
adult(51,private,13,exec_managerial,white,male,50,united_states).
adult(36,private,13,other_service,black,male,36,united_states).
adult(58,self_emp_inc,9,sales,white,female,35,united_states).
adult(37,private,9,craft_repair,white,male,40,united_states).
adult(54,self_emp_inc,4,machine_op_inspct,white,male,40,united_states).
adult(37,private,13,exec_managerial,black,male,60,united_states).
adult(28,private,15,prof_specialty,white,male,55,united_states).
adult(41,private,13,exec_managerial,white,male,50,iran).
adult(38,local_gov,14,exec_managerial,white,male,70,united_states).
adult(40,private,13,prof_specialty,white,male,40,united_states).
adult(58,private,9,adm_clerical,white,male,45,united_states).
adult(40,private,12,tech_support,white,male,60,united_states).
adult(41,private,15,prof_specialty,white,female,40,united_states).
adult(42,self_emp_not_inc,9,farming_fishing,asian_pac_islander,male,40,cambodia).
adult(37,self_emp_inc,10,exec_managerial,asian_pac_islander,male,75,thailand).
adult(64,private,9,exec_managerial,white,male,40,united_states).
adult(33,private,9,craft_repair,white,female,40,united_states).
adult(61,private,9,exec_managerial,white,male,40,united_states).
adult(44,private,10,craft_repair,white,male,40,united_states).
adult(24,private,10,machine_op_inspct,white,female,48,united_states).
adult(42,local_gov,10,craft_repair,white,male,40,united_states).
adult(57,federal_gov,14,sales,white,male,40,united_states).
adult(41,private,15,prof_specialty,white,male,60,united_states).
adult(48,private,13,adm_clerical,white,male,40,united_states).
adult(31,private,9,transport_moving,white,male,45,united_states).
adult(55,private,9,sales,white,male,40,united_states).
adult(35,private,12,adm_clerical,white,male,40,united_states).
adult(41,self_emp_inc,10,farming_fishing,white,male,54,united_states).
adult(34,private,14,exec_managerial,asian_pac_islander,male,35,taiwan).
adult(36,self_emp_not_inc,13,prof_specialty,black,female,40,united_states).
adult(43,private,10,prof_specialty,white,female,50,united_states).
adult(38,private,11,craft_repair,white,male,40,united_states).
adult(36,state_gov,9,protective_serv,white,male,40,united_states).
adult(33,private,13,exec_managerial,white,male,40,united_states).
adult(33,private,13,exec_managerial,white,male,40,united_states).
adult(38,federal_gov,9,adm_clerical,white,male,40,united_states).
adult(40,private,11,tech_support,white,male,40,united_states).
adult(62,private,14,prof_specialty,white,male,40,united_states).
adult(43,private,13,exec_managerial,white,male,45,united_states).
adult(57,private,13,exec_managerial,white,female,45,united_states).
adult(40,state_gov,11,machine_op_inspct,white,male,38,united_states).
adult(44,private,10,adm_clerical,white,female,6,united_states).
adult(35,private,9,other_service,white,female,40,united_states).
adult(25,private,13,exec_managerial,white,male,55,united_states).
adult(52,self_emp_inc,13,exec_managerial,white,male,50,united_states).
adult(50,state_gov,13,protective_serv,white,male,40,united_states).
adult(41,private,14,exec_managerial,white,male,65,united_states).
adult(46,private,16,exec_managerial,white,male,60,united_states).
adult(35,private,8,craft_repair,white,male,50,united_states).
adult(32,state_gov,13,exec_managerial,white,female,40,united_states).
adult(63,self_emp_inc,9,exec_managerial,white,male,40,united_states).
adult(30,private,12,other_service,white,female,25,united_states).
adult(33,private,14,prof_specialty,white,male,50,united_states).
adult(44,private,10,prof_specialty,white,male,40,united_states).
adult(45,self_emp_inc,10,craft_repair,white,male,55,united_states).
adult(60,private,9,craft_repair,white,male,40,united_states).
adult(44,self_emp_not_inc,9,sales,white,female,40,united_states).
adult(40,private,11,machine_op_inspct,asian_pac_islander,male,40,united_states).
adult(49,private,14,exec_managerial,white,male,45,united_states).
adult(30,private,13,tech_support,white,female,16,united_states).
adult(60,private,10,prof_specialty,white,male,40,united_states).
adult(38,private,13,sales,white,male,60,united_states).
adult(34,private,10,prof_specialty,white,male,50,united_states).
adult(34,private,13,prof_specialty,white,male,50,united_states).
adult(38,self_emp_inc,13,exec_managerial,white,male,80,united_states).
adult(50,private,9,exec_managerial,white,male,50,united_states).
adult(37,local_gov,10,tech_support,white,male,45,united_states).
adult(44,private,10,machine_op_inspct,white,male,58,united_states).
adult(42,private,13,exec_managerial,white,male,40,united_states).
adult(41,private,12,exec_managerial,white,female,50,united_states).
adult(67,private,15,prof_specialty,white,male,48,united_states).
adult(33,federal_gov,11,craft_repair,black,female,40,united_states).
adult(54,private,13,sales,white,male,35,united_states).
adult(47,private,10,prof_specialty,white,male,50,united_states).
adult(52,self_emp_not_inc,13,prof_specialty,white,male,60,united_states).
adult(37,private,11,craft_repair,white,male,40,united_states).
adult(29,private,13,exec_managerial,white,male,40,united_states).
adult(57,private,9,sales,white,male,40,united_states).
adult(52,private,6,craft_repair,white,male,47,united_states).
adult(60,private,4,transport_moving,white,male,48,united_states).
adult(31,private,13,prof_specialty,white,male,40,canada).
adult(42,self_emp_not_inc,15,prof_specialty,white,male,50,united_states).
adult(51,private,14,craft_repair,white,male,40,united_states).
adult(46,private,15,prof_specialty,white,male,45,united_states).
adult(34,private,9,sales,white,male,45,united_states).
adult(33,private,10,exec_managerial,white,male,40,united_states).
adult(49,private,13,sales,white,male,26,united_states).
adult(43,private,10,craft_repair,white,male,60,united_states).
adult(30,private,13,adm_clerical,black,female,40,united_states).
adult(33,private,13,exec_managerial,white,male,60,united_states).
adult(52,self_emp_not_inc,16,prof_specialty,white,male,60,united_states).
adult(36,private,10,sales,white,male,50,united_states).
adult(50,self_emp_inc,16,prof_specialty,white,male,40,united_states).
adult(30,state_gov,13,tech_support,white,male,40,united_states).
adult(35,private,16,prof_specialty,asian_pac_islander,male,40,taiwan).
adult(43,private,9,machine_op_inspct,white,male,40,united_states).
adult(44,self_emp_not_inc,8,handlers_cleaners,black,male,40,united_states).
adult(42,private,12,prof_specialty,white,female,40,united_states).
adult(42,private,9,craft_repair,black,male,40,united_states).
adult(33,private,13,exec_managerial,white,male,40,united_states).
adult(50,self_emp_inc,9,sales,white,male,50,united_states).
adult(37,private,11,craft_repair,white,male,40,portugal).
adult(34,self_emp_not_inc,9,craft_repair,white,male,40,united_states).
adult(35,private,14,prof_specialty,white,male,60,united_states).
adult(31,private,14,tech_support,white,male,40,united_states).
adult(46,private,16,prof_specialty,white,female,65,united_states).
adult(44,private,13,exec_managerial,white,female,50,united_states).
adult(34,private,13,exec_managerial,white,male,45,united_states).
adult(50,local_gov,9,exec_managerial,white,male,42,united_states).
adult(42,private,13,exec_managerial,white,male,45,united_states).
adult(42,private,13,tech_support,white,male,40,united_states).
adult(42,private,14,exec_managerial,white,female,50,united_states).
adult(42,local_gov,13,prof_specialty,white,female,40,united_states).
adult(55,private,9,transport_moving,white,male,40,united_states).
adult(29,state_gov,13,exec_managerial,white,male,40,united_states).
adult(54,private,9,transport_moving,white,male,40,united_states).
adult(46,federal_gov,9,adm_clerical,white,female,40,united_states).
adult(59,local_gov,9,adm_clerical,white,female,38,united_states).
adult(53,self_emp_inc,16,exec_managerial,white,male,70,united_states).
adult(51,private,13,sales,white,male,55,united_states).
adult(37,private,11,tech_support,white,female,24,united_states).
adult(43,private,13,sales,white,male,50,united_states).
adult(40,private,11,exec_managerial,white,male,50,united_states).
adult(40,private,13,sales,other,female,55,united_states).
adult(48,private,11,tech_support,white,male,50,united_states).
adult(60,private,9,transport_moving,white,male,60,united_states).
adult(46,private,14,tech_support,white,male,35,united_states).
adult(43,private,13,exec_managerial,white,male,40,england).
adult(32,private,9,craft_repair,white,male,48,united_states).
adult(33,private,13,prof_specialty,white,male,47,united_states).
adult(64,private,13,prof_specialty,white,male,40,united_states).
adult(56,private,10,craft_repair,white,male,50,united_states).
adult(47,private,9,transport_moving,white,male,50,united_states).
adult(57,private,9,transport_moving,white,male,42,united_states).
adult(53,private,10,adm_clerical,white,female,40,united_states).
adult(41,private,13,prof_specialty,white,female,50,united_states).
adult(51,private,10,prof_specialty,white,male,40,united_states).
adult(55,private,9,craft_repair,white,male,40,united_states).
adult(37,private,13,exec_managerial,white,male,45,united_states).
adult(61,private,14,prof_specialty,white,female,40,united_states).
adult(48,state_gov,16,prof_specialty,white,male,50,united_states).
adult(59,private,9,other_service,white,male,40,united_states).
adult(49,private,13,exec_managerial,white,female,56,united_states).
adult(39,private,10,farming_fishing,white,male,50,united_states).
adult(44,private,13,exec_managerial,white,male,40,united_states).
adult(71,self_emp_not_inc,14,sales,white,male,40,united_states).
adult(51,self_emp_not_inc,13,sales,asian_pac_islander,male,40,china).
adult(41,private,13,exec_managerial,white,male,60,united_states).
adult(39,private,9,transport_moving,white,male,40,united_states).
adult(32,private,13,adm_clerical,white,male,40,philippines).
adult(38,private,13,sales,white,male,50,united_states).
adult(37,private,13,prof_specialty,white,male,50,united_states).
adult(42,self_emp_not_inc,15,farming_fishing,white,male,65,united_states).
adult(30,private,13,exec_managerial,white,male,45,united_states).
adult(39,private,13,exec_managerial,white,male,45,united_states).
adult(67,self_emp_inc,9,exec_managerial,asian_pac_islander,male,40,united_states).
adult(51,private,14,exec_managerial,white,male,60,united_states).
adult(37,private,7,machine_op_inspct,white,male,44,united_states).
adult(37,private,9,craft_repair,white,male,99,united_states).
adult(41,private,15,prof_specialty,white,male,40,united_states).
adult(31,private,13,sales,white,male,40,united_states).
adult(38,self_emp_inc,9,exec_managerial,white,male,40,united_states).
adult(36,self_emp_inc,13,exec_managerial,white,female,45,united_states).
adult(44,state_gov,9,prof_specialty,white,female,40,united_states).
adult(43,private,14,exec_managerial,white,male,43,united_states).
adult(44,self_emp_inc,10,sales,white,male,70,united_states).
adult(33,self_emp_not_inc,13,exec_managerial,white,male,40,united_states).
adult(42,private,12,exec_managerial,white,male,40,united_states).
adult(35,self_emp_inc,10,sales,white,male,60,united_states).
adult(48,private,13,exec_managerial,asian_pac_islander,male,40,india).
adult(34,private,9,craft_repair,white,male,35,united_states).
adult(67,private,13,exec_managerial,white,male,40,united_states).
adult(40,state_gov,14,prof_specialty,white,male,35,united_states).
adult(45,local_gov,9,protective_serv,white,male,40,united_states).
adult(47,private,9,adm_clerical,white,male,50,united_states).
adult(56,private,9,exec_managerial,white,male,55,united_states).
adult(48,federal_gov,13,exec_managerial,white,male,58,united_states).
adult(39,self_emp_inc,13,exec_managerial,white,male,50,united_states).
